### ISSUE TITLE
WM_SETTEXT Can't Send string

### ISSUE THREAD

**Issue by w4po** [stefankueng/sendmessage#17]
I can't send a WM_SETTEXT message to Notepad to set the text, it just clears what was written.

![image](https://github.com/stefankueng/sendmessage/assets/6666887/55b2f5c8-0297-4de2-bef5-4a98e8f0b9fd)

**Comment by stefankueng** [comment]
LPARAM is a pointer to data.
The pointer however is to the text in the SendMessage.exe process. That address is not accessible in the target process.

You can not send text like that, sorry.
