### ISSUE TITLE
Use CLang + MinGW-w64 for build

### ISSUE THREAD

**Issue by KOLANICH** [stefankueng/sendmessage#5]
VisualStudio is a non-free toolchain.

**Comment by stefankueng** [comment]
Visual Studio is available for free when used in open source projects like this:
https://visualstudio.microsoft.com/vs/community/

**Comment by KOLANICH** [comment]
VS is proprietary, has telemetry and cannot be even downloaded as an ISO image (to be run in an isolated system to prevent M$ from collecting telemetry) without running a downloader with telemetry. Usage of VS is disrespect to oneself. Promoting it is disrespect to other people.
