### ISSUE TITLE
Crash when dragging target across text editor windows

### ISSUE THREAD

**Issue by da40** [stefankueng/sendmessage#7]
The accessible name of a text editor window is its contents, which overflows the buffer in DisplayInfoOnFoundWindow.  This can be easily fixed as shown in this extract, where lines containing szAccName are changed or new:

`bool CMainDlg::DisplayInfoOnFoundWindow(HWND hwndFoundWindow)
{
    RECT        rect;              // Rectangle area of the found window.
    TCHAR       szText[512];
    TCHAR       szClassName[100];
    TCHAR       szAccName[100];

    // Get the screen coordinates of the rectangle of the found window.
    GetWindowRect(hwndFoundWindow, &rect);

    // Get the class name of the found window.
    GetClassName(hwndFoundWindow, szClassName, _countof(szClassName));

    // Get its accessible name.
    _tcsncpy_s(szAccName, _countof(szAccName), CAccessibleName(hwndFoundWindow).c_str(), _TRUNCATE);

    // Display some information on the found window.
    _stprintf_s
        (
        szText, _countof(szText), _T("Window Handle == 0x%p\r\nClass Name : %s\r\nAccessible Name : %s\r\nRECT == { Left: %d, Top: %d, Right: %d, Bottom: %d }\r\n"),
        hwndFoundWindow,
        szClassName,
        szAccName,
        rect.left,
        rect.top,
        rect.right,
        rect.bottom
        );
`

**Comment by iljavs** [comment]
Ran into this too a few days ago. Any update on fixing this issue?

**Comment by stefankueng** [comment]
was fixed with d98a50432cb1732258dc58505c13710935b8259d
