### ISSUE TITLE
[Help] How to send CTRL+C (graceful shutdown) to a opened .jar on CMD

### ISSUE THREAD

**Issue by VegethB** [stefankueng/sendmessage#9]
I can't figure out how to send a "`CTRL+C`" to the open java window to tell it to do a graceful shutdown (a batch running this .jar in a CMD with a specific window title).
The problem is that the only command I find, closes the window instant.
In theory the value "0x03" should see it as "`CTRL+C`" but I don't know where to write it.

Thanks in advance

**Comment by stefankueng** [comment]
you could try the [WM_COPY](https://docs.microsoft.com/en-us/windows/win32/dataxchg/wm-copy) message.
SendMessage is a tool to send window messages, not keystrokes like `Ctrl+C`

**Comment by VegethB** [comment]
I badly explained myself...
In a normal situation, to stop the process running on the Windows CMD, press "CTRL + C" which sends the process to graceful shutdown. So my attempt was to send the keystroke through this program... But if you know the right "message" that causes Java software running under CMD to go into graceful shutdown, then I'd be happy.
Thanks anyway for the answer, tomorrow I'll try and see if it works with WM_Copy anyway.

**Comment by VegethB** [comment]
After finding some time, what I wanted to do is not a message, it is a signal.
![image](https://user-images.githubusercontent.com/17975351/190396577-37a378ec-614c-4980-9847-a40d164f9c18.png)
---------------
`SIGINT` I don't know if its version exists in message (which is what I was asking)

**Comment by xiaoguyin** [comment]
小古银已收到
